import type { WorkflowStep } from "@/types";

export const CRM_PIPELINE_STAGES: WorkflowStep[] = [
  {
    id: "s0-research",
    agentId: "research-agent",
    agentName: "Research-Agent",
    promptTemplate: "Conduct market research and competitor analysis for: {{input}}",
    dependsOn: [],
    outputKey: "research",
    metadata: {
      stageNumber: "0",
      qualityThreshold: 8,
      leadAgent: "research-agent",
      model: "sonnet-4-6",
    },
  },
  {
    id: "s1-orchestrator",
    agentId: "orchestrator",
    agentName: "Orchestrator",
    promptTemplate: "Based on research:\n{{step_s0-research_output}}\n\nClarify requirements for: {{input}}\nAsk 5-10 targeted questions.",
    dependsOn: ["s0-research"],
    outputKey: "requirements",
    metadata: {
      stageNumber: "1",
      qualityThreshold: 8,
      leadAgent: "orchestrator",
      model: "sonnet-4-6",
    },
  },
  {
    id: "s2-pm",
    agentId: "pm-agent",
    agentName: "PM-Agent",
    promptTemplate: "Create detailed PRD and Jira epic/story structure based on:\n{{step_s1-orchestrator_output}}",
    dependsOn: ["s1-orchestrator"],
    outputKey: "prd",
    metadata: {
      stageNumber: "2",
      qualityThreshold: 8,
      leadAgent: "pm-agent",
      model: "sonnet-4-6",
    },
  },
  {
    id: "s3-architect",
    agentId: "architect-agent",
    agentName: "Architect-Agent",
    promptTemplate: "Design system architecture and ADRs based on PRD:\n{{step_s2-pm_output}}",
    dependsOn: ["s2-pm"],
    outputKey: "architecture",
    metadata: {
      stageNumber: "3",
      qualityThreshold: 8,
      leadAgent: "architect-agent",
      model: "sonnet-4-6",
    },
  },
  {
    id: "s3.5-cyber",
    agentId: "cyber-agent",
    agentName: "Cyber-Agent",
    promptTemplate: "Create threat model based on architecture:\n{{step_s3-architect_output}}\n\nMandatory if public API, auth, or payments involved.",
    dependsOn: ["s3-architect"],
    outputKey: "threat_model",
    metadata: {
      stageNumber: "3.5",
      qualityThreshold: 8,
      leadAgent: "cyber-agent",
      model: "sonnet-4-6",
      conditional: "public API / auth / payments",
    },
  },
  {
    id: "s4-backend",
    agentId: "backend-agent",
    agentName: "Backend-Agent",
    promptTemplate: "Create backend implementation based on:\nArchitecture: {{step_s3-architect_output}}\nThreat model: {{step_s3.5-cyber_output}}",
    dependsOn: ["s3.5-cyber"],
    outputKey: "backend_plan",
    metadata: {
      stageNumber: "4",
      qualityThreshold: 8,
      leadAgent: "backend-agent",
      model: "sonnet-4-6",
      isParallel: true,
      group: "implementation",
    },
  },
  {
    id: "s4-frontend",
    agentId: "frontend-agent",
    agentName: "Frontend-Agent",
    promptTemplate: "Create frontend implementation based on:\nArchitecture: {{step_s3-architect_output}}\nThreat model: {{step_s3.5-cyber_output}}",
    dependsOn: ["s3.5-cyber"],
    outputKey: "frontend_plan",
    metadata: {
      stageNumber: "4",
      qualityThreshold: 8,
      leadAgent: "frontend-agent",
      model: "sonnet-4-6",
      isParallel: true,
      group: "implementation",
    },
  },
  {
    id: "s4-designer",
    agentId: "designer-agent",
    agentName: "Designer-Agent",
    promptTemplate: "Create UI/UX design based on:\nArchitecture: {{step_s3-architect_output}}\nPRD: {{step_s2-pm_output}}",
    dependsOn: ["s3.5-cyber"],
    outputKey: "design",
    metadata: {
      stageNumber: "4",
      qualityThreshold: 8,
      leadAgent: "designer-agent",
      model: "sonnet-4-6",
      isParallel: true,
      group: "implementation",
    },
  },
  {
    id: "s4.5-checkpoint",
    agentId: "orchestrator",
    agentName: "Human Checkpoint",
    promptTemplate: "⚠️ HUMAN CHECKPOINT — Review implementation outputs before proceeding.\nBackend: {{step_s4-backend_output}}\nFrontend: {{step_s4-frontend_output}}\nDesign: {{step_s4-designer_output}}",
    dependsOn: ["s4-backend", "s4-frontend", "s4-designer"],
    outputKey: "checkpoint_approval",
    metadata: {
      stageNumber: "4.5",
      qualityThreshold: 0,
      leadAgent: "orchestrator",
      model: "sonnet-4-6",
      isCheckpoint: true,
    },
  },
  {
    id: "s5-qa",
    agentId: "qa-agent",
    agentName: "QA-Agent",
    promptTemplate: "Generate attack plan (minimum 12 findings) for:\nBackend: {{step_s4-backend_output}}\nFrontend: {{step_s4-frontend_output}}\nDesign: {{step_s4-designer_output}}",
    dependsOn: ["s4.5-checkpoint"],
    outputKey: "test_plan",
    metadata: {
      stageNumber: "5",
      qualityThreshold: 8,
      leadAgent: "qa-agent",
      model: "sonnet-4-6",
    },
  },
  {
    id: "s5.5-cyber-audit",
    agentId: "cyber-agent",
    agentName: "Cyber-Agent",
    promptTemplate: "Deep security audit based on:\nBackend: {{step_s4-backend_output}}\nQA findings: {{step_s5-qa_output}}",
    dependsOn: ["s5-qa"],
    outputKey: "security_audit",
    metadata: {
      stageNumber: "5.5",
      qualityThreshold: 8,
      leadAgent: "cyber-agent",
      model: "sonnet-4-6",
    },
  },
  {
    id: "s6-devops",
    agentId: "devops-agent",
    agentName: "DevOps-Agent",
    promptTemplate: "Create infrastructure, CI/CD, and rollback plan based on:\nArchitecture: {{step_s3-architect_output}}\nBackend: {{step_s4-backend_output}}\nSecurity audit: {{step_s5.5-cyber-audit_output}}",
    dependsOn: ["s5.5-cyber-audit"],
    outputKey: "infrastructure",
    metadata: {
      stageNumber: "6",
      qualityThreshold: 8,
      leadAgent: "devops-agent",
      model: "sonnet-4-6",
    },
  },
  {
    id: "s7-consolidation",
    agentId: "orchestrator",
    agentName: "Orchestrator",
    promptTemplate: "Final consolidation and weekly report.\nAll outputs: Research→{{step_s0-research_output}}, PRD→{{step_s2-pm_output}}, Architecture→{{step_s3-architect_output}}, QA→{{step_s5-qa_output}}, DevOps→{{step_s6-devops_output}}",
    dependsOn: ["s6-devops"],
    outputKey: "final_report",
    metadata: {
      stageNumber: "7",
      qualityThreshold: 8,
      leadAgent: "orchestrator",
      model: "sonnet-4-6",
    },
  },
];

export const CRM_PIPELINE_TEMPLATE = {
  name: "Beauty CRM Full Pipeline",
  description: "10-stage pipeline: Research → PM → Architect → Cyber → Backend/Frontend/Designer (parallel) → Human Checkpoint → QA → Cyber Audit → DevOps → Consolidation",
  steps: CRM_PIPELINE_STAGES,
};
